// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgkkmlmznkitetgqxsdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJna2ttbG16bmtpdGV0Z3F4c2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzc5NDUsImV4cCI6MjA1OTQ1Mzk0NX0.4sWhhv0Yn5EcZ1AaSrHWGoYVNHEDadtODtSJl9GfF7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);